import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { PageHeader } from "@/components/page-header";
import { createAdminClient } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";

async function invite(formData: FormData) { "use server"; const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/login"); const email = String(formData.get("email") || "").trim().toLowerCase(); const role = String(formData.get("role") || "field"); if (!email || !["admin","estimator","field","read_only"].includes(role)) return; const admin = createAdminClient(); const appUrl = process.env.NEXT_PUBLIC_APP_URL; const { data, error } = await admin.auth.admin.inviteUserByEmail(email, { redirectTo: appUrl ? `${appUrl}/auth/confirm?next=/update-password` : undefined, data: { business_owner_id: user.id } }); if (error || !data.user) throw new Error(error?.message || "Could not invite user"); await admin.from("business_members").upsert({ business_owner_id:user.id,user_id:data.user.id,email,role,status:"invited",invited_by:user.id }, { onConflict:"user_id" }); revalidatePath("/settings/team"); }

export default async function TeamPage() { const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/login"); const { data: members } = await supabase.from("business_members").select("id,user_id,email,full_name,role,status,created_at").eq("business_owner_id", user.id).neq("role","owner").order("created_at"); return <div className="page-wrap page-wrap--narrow"><PageHeader eyebrow="Owner controls" title="Team and demo logins"/><form action={invite} className="panel form-grid"><label>Email<input name="email" type="email" required placeholder="employee@example.com"/></label><label>Access level<select name="role" defaultValue="field"><option value="field">Field employee</option><option value="estimator">Estimator</option><option value="admin">Administrator</option><option value="read_only">Demo — read only</option></select></label><div className="form-actions span-2"><button className="button button--gold">Send secure invitation</button></div></form><section className="panel" style={{marginTop:22}}><h2>People with access</h2><div className="record-list">{(members ?? []).map((member) => <div key={member.id} style={{padding:"14px 0",borderBottom:"1px solid var(--line)"}}><strong>{member.full_name || member.email}</strong><span>{member.role.replaceAll("_"," ")} · {member.status}</span></div>)}{!members?.length && <p className="muted">No employee or demo accounts invited yet.</p>}</div></section></div>; }
