import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { PageHeader } from "@/components/page-header";
import { createAdminClient } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";

async function invite(formData: FormData) { "use server"; const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/login"); const email = String(formData.get("email") || "").trim().toLowerCase(); const role = String(formData.get("role") || "employee"); if (!email || !["manager","employee","demo"].includes(role)) return; const admin = createAdminClient(); const appUrl = process.env.NEXT_PUBLIC_APP_URL; const { data, error } = await admin.auth.admin.inviteUserByEmail(email, { redirectTo: appUrl ? `${appUrl}/auth/confirm` : undefined, data: { invited_by: user.id } }); if (error || !data.user) throw new Error(error?.message || "Could not invite user"); const permissions = role === "demo" ? { customers:true,estimates:true,projects:true,payments:false,settings:false,read_only:true } : { customers:true,estimates:true,projects:true,payments:role === "manager",settings:role === "manager",read_only:false }; await admin.from("team_access").upsert({ user_id:data.user.id,owner_id:user.id,email,role,permissions,active:true }, { onConflict:"user_id" }); revalidatePath("/settings/team"); }

export default async function TeamPage() { const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/login"); const { data: members } = await supabase.from("team_access").select("user_id,email,display_name,role,permissions,active,created_at").eq("owner_id", user.id).order("created_at"); return <div className="page-wrap page-wrap--narrow"><PageHeader eyebrow="Owner controls" title="Team and demo logins" description="Invite employees, managers, or a safe read-only demo account. You remain in control of access."/><form action={invite} className="panel form-grid"><label>Email<input name="email" type="email" required placeholder="employee@example.com"/></label><label>Access level<select name="role" defaultValue="employee"><option value="employee">Employee</option><option value="manager">Manager</option><option value="demo">Demo — read only</option></select></label><div className="form-actions span-2"><button className="button button--gold">Send secure invitation</button></div></form><section className="panel" style={{marginTop:22}}><h2>People with access</h2><div className="record-list">{(members ?? []).map((member) => <div key={member.user_id} style={{padding:"14px 0",borderBottom:"1px solid var(--line)"}}><strong>{member.display_name || member.email}</strong><span>{member.role} · {member.active ? "Active" : "Disabled"}</span></div>)}{!members?.length && <p className="muted">No employee or demo accounts invited yet.</p>}</div></section></div>; }
