"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Plus, Save, Trash2 } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { estimateTotals, money } from "@/lib/money";
import type { EstimateItemDraft } from "@/lib/types";

const blankItem = (markup = 20): EstimateItemDraft => ({ item_type:"material", category:"", description:"", quantity:1, unit:"each", unit_cost:0, markup_rate:markup, taxable:true, vendor:"", vendor_sku:"", vendor_url:"", private_notes:"" });

export function EstimateBuilder({ customers, defaults, selectedCustomer }: { customers:any[]; defaults:{ tax_rate:number; markup_rate:number }; selectedCustomer?:string }) {
  const router = useRouter(); const supabase = createClient();
  const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  const [customerId,setCustomerId]=useState(selectedCustomer??""); const [title,setTitle]=useState(""); const [address,setAddress]=useState("");
  const [scope,setScope]=useState(""); const [exclusions,setExclusions]=useState(""); const [notes,setNotes]=useState(""); const [privateNotes,setPrivateNotes]=useState(""); const [schedule,setSchedule]=useState("30% deposit to reserve scheduling; progress payments tied to completed phases; final balance due at final walkthrough.");
  const [taxRate,setTaxRate]=useState(Number(defaults.tax_rate||0)); const [markupRate,setMarkupRate]=useState(Number(defaults.markup_rate||20));
  const [items,setItems]=useState<EstimateItemDraft[]>([blankItem(Number(defaults.markup_rate||20))]);
  const totals=useMemo(()=>estimateTotals(items,taxRate),[items,taxRate]);
  function patch(index:number, values:Partial<EstimateItemDraft>){ setItems(current=>current.map((item,i)=>i===index?{...item,...values}:item)); }
  function addItem(){setItems(current=>[...current,blankItem(markupRate)]);} function removeItem(index:number){setItems(current=>current.filter((_,i)=>i!==index));}
  async function save(){
    setError(""); if(!customerId||!title.trim()){setError("Choose a customer and enter a project title.");return;} if(!items.some(i=>i.description.trim())){setError("Add at least one line item.");return;}
    setBusy(true); const {data:{user}}=await supabase.auth.getUser(); if(!user){setError("Your session expired. Sign in again.");setBusy(false);return;}
    const {data:estimate,error:estimateError}=await supabase.from("estimates").insert({owner_id:user.id,customer_id:customerId,title,project_address:address||null,scope:scope||null,exclusions:exclusions||null,customer_notes:notes||null,private_notes:privateNotes||null,payment_schedule:schedule||null,tax_rate:taxRate,default_markup_rate:markupRate,subtotal:totals.subtotal,markup_total:totals.markupTotal,tax_total:totals.taxTotal,total:totals.total}).select("id").single();
    if(estimateError||!estimate){setError(estimateError?.message||"Could not save estimate.");setBusy(false);return;}
    const rows=items.filter(i=>i.description.trim()).map((item,index)=>({owner_id:user.id,estimate_id:estimate.id,sort_order:index,...item,line_subtotal:item.quantity*item.unit_cost,line_markup:item.quantity*item.unit_cost*(item.markup_rate/100),line_total:item.quantity*item.unit_cost*(1+item.markup_rate/100)}));
    const {error:itemError}=await supabase.from("estimate_items").insert(rows); if(itemError){setError(itemError.message);setBusy(false);return;}
    router.push(`/estimates/${estimate.id}`); router.refresh();
  }
  return <div className="builder-layout"><div className="builder-main">
    <section className="panel form-grid"><label className="span-2">Customer<select value={customerId} onChange={e=>setCustomerId(e.target.value)} required><option value="">Choose a customer…</option>{customers.map(c=><option key={c.id} value={c.id}>{c.first_name} {c.last_name}{c.company_name?` — ${c.company_name}`:""}</option>)}</select></label><label className="span-2">Project title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Primary bathroom remodel" /></label><label className="span-2">Project address<input value={address} onChange={e=>setAddress(e.target.value)} placeholder="Use the customer's address or enter another jobsite" /></label></section>
    <section className="panel"><div className="panel-heading"><div><h2>Pricing</h2><p>Materials, labor, subcontractors, allowances, fees, and other costs.</p></div><button className="button button--outline" type="button" onClick={addItem}><Plus size={16}/> Add line</button></div>
      <div className="item-list">{items.map((item,index)=><article className="line-item" key={index}><div className="line-item-top"><select value={item.item_type} onChange={e=>patch(index,{item_type:e.target.value as any})}><option value="material">Material</option><option value="labor">Labor</option><option value="subcontractor">Subcontractor</option><option value="allowance">Allowance</option><option value="fee">Fee</option><option value="other">Other</option></select><input className="grow" value={item.description} onChange={e=>patch(index,{description:e.target.value})} placeholder="Description"/><button type="button" className="icon-button danger" onClick={()=>removeItem(index)} aria-label="Remove"><Trash2 size={17}/></button></div><div className="line-item-grid"><label>Category<input value={item.category} onChange={e=>patch(index,{category:e.target.value})}/></label><label>Qty<input type="number" min="0" step="0.01" value={item.quantity} onChange={e=>patch(index,{quantity:Number(e.target.value)})}/></label><label>Unit<input value={item.unit} onChange={e=>patch(index,{unit:e.target.value})}/></label><label>Unit cost<input type="number" min="0" step="0.01" value={item.unit_cost} onChange={e=>patch(index,{unit_cost:Number(e.target.value)})}/></label><label>Markup %<input type="number" min="0" step="0.1" value={item.markup_rate} onChange={e=>patch(index,{markup_rate:Number(e.target.value)})}/></label><label className="checkbox"><input type="checkbox" checked={item.taxable} onChange={e=>patch(index,{taxable:e.target.checked})}/> Taxable</label><label>Vendor<input value={item.vendor} onChange={e=>patch(index,{vendor:e.target.value})} placeholder="Lowe's"/></label><label>SKU / item #<input value={item.vendor_sku} onChange={e=>patch(index,{vendor_sku:e.target.value})}/></label><label className="span-2">Vendor URL<input value={item.vendor_url} onChange={e=>patch(index,{vendor_url:e.target.value})}/></label><label className="span-2">Private line note<input value={item.private_notes} onChange={e=>patch(index,{private_notes:e.target.value})} placeholder="Not shown to customer"/></label></div><div className="line-total">Customer price: <strong>{money(item.quantity*item.unit_cost*(1+item.markup_rate/100))}</strong></div></article>)}</div>
    </section>
    <section className="panel form-grid"><label className="span-2">Detailed scope of work<textarea rows={10} value={scope} onChange={e=>setScope(e.target.value)} placeholder="Describe exactly what Ironwood will provide and perform."/></label><label className="span-2">Exclusions and owner-supplied items<textarea rows={5} value={exclusions} onChange={e=>setExclusions(e.target.value)}/></label><label className="span-2">Customer-facing notes<textarea rows={4} value={notes} onChange={e=>setNotes(e.target.value)}/></label><label className="span-2">Payment schedule<textarea rows={4} value={schedule} onChange={e=>setSchedule(e.target.value)}/></label><label className="span-2">Private Ironwood notes<textarea rows={4} value={privateNotes} onChange={e=>setPrivateNotes(e.target.value)} placeholder="Never shown on the customer proposal."/></label></section>
  </div><aside className="builder-summary panel"><h2>Estimate total</h2><label>Default markup %<input type="number" value={markupRate} onChange={e=>setMarkupRate(Number(e.target.value))}/></label><label>Sales tax %<input type="number" value={taxRate} onChange={e=>setTaxRate(Number(e.target.value))}/></label><dl className="totals"><div><dt>Base cost</dt><dd>{money(totals.subtotal)}</dd></div><div><dt>Markup</dt><dd>{money(totals.markupTotal)}</dd></div><div><dt>Tax</dt><dd>{money(totals.taxTotal)}</dd></div><div className="grand"><dt>Total</dt><dd>{money(totals.total)}</dd></div></dl>{error&&<p className="error-box">{error}</p>}<button onClick={save} disabled={busy} className="button button--gold button--block"><Save size={17}/>{busy?"Saving…":"Save estimate"}</button><p className="fine-print">Private notes and raw cost details stay inside Ironwood.</p></aside></div>;
}
