"use client";
import { FormEvent, useEffect, useState } from "react";
import { CheckCircle2 } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { money } from "@/lib/money";
import { IronwoodLogo } from "./ironwood-logo";

export function PublicProposal({ token, proposal }: { token:string; proposal:any }) {
 const [accepted,setAccepted]=useState(Boolean(proposal.estimate.accepted_at)); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const supabase=createClient();
 useEffect(()=>{supabase.rpc("record_estimate_view",{p_token:token,p_user_agent:navigator.userAgent});},[supabase,token]);
 async function accept(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const form=new FormData(e.currentTarget);const {error}=await supabase.rpc("accept_public_estimate",{p_token:token,p_name:String(form.get("name")||""),p_email:String(form.get("email")||""),p_note:String(form.get("note")||"")});setBusy(false);if(error)setError(error.message);else setAccepted(true);}
 const e=proposal.estimate; const c=proposal.customer; const business=proposal.business||{};
 return <main className="proposal-page"><header className="proposal-header"><div className="proposal-header-inner"><IronwoodLogo/><div><small>PROPOSAL</small><strong>{e.estimate_number}</strong></div></div></header><article className="proposal-sheet"><section className="proposal-hero"><div className="eyebrow">Prepared for {c.first_name} {c.last_name}</div><h1>{e.title}</h1><p>{e.project_address}</p><div className="proposal-total"><span>Project investment</span><strong>{money(e.total)}</strong></div></section><section className="proposal-section"><h2>Scope of work</h2><div className="preline">{e.scope||"Scope not entered."}</div></section><section className="proposal-section"><h2>Investment details</h2><div className="table-wrap"><table><thead><tr><th>Description</th><th>Quantity</th><th>Amount</th></tr></thead><tbody>{proposal.items.map((i:any)=><tr key={i.id}><td>{i.description}<small>{i.category}</small></td><td>{i.quantity} {i.unit}</td><td>{money(i.line_total)}</td></tr>)}</tbody></table></div><dl className="totals totals--right"><div><dt>Subtotal</dt><dd>{money(Number(e.subtotal)+Number(e.markup_total))}</dd></div><div><dt>Tax</dt><dd>{money(e.tax_total)}</dd></div><div className="grand"><dt>Total</dt><dd>{money(e.total)}</dd></div></dl></section>{e.exclusions&&<section className="proposal-section"><h2>Exclusions and owner-supplied items</h2><div className="preline">{e.exclusions}</div></section>}{e.payment_schedule&&<section className="proposal-section"><h2>Payment schedule</h2><div className="preline">{e.payment_schedule}</div></section>}{e.customer_notes&&<section className="proposal-section"><h2>Additional notes</h2><div className="preline">{e.customer_notes}</div></section>}<section className="proposal-section acceptance"><h2>Proposal acceptance</h2>{accepted?<div className="accepted-box"><CheckCircle2/><div><strong>Proposal accepted</strong><p>Thank you. Ironwood Remodeling has received the acceptance and will follow up about scheduling and next steps.</p></div></div>:<form onSubmit={accept} className="form-grid"><p className="span-2">By submitting this form, the customer confirms acceptance of the scope, pricing, exclusions, and payment schedule shown above.</p><label>Full name<input name="name" required/></label><label>Email<input name="email" type="email" required defaultValue={c.email||""}/></label><label className="span-2">Optional note<textarea name="note" rows={3}/></label><label className="checkbox span-2"><input type="checkbox" required/> I am authorized to approve this proposal.</label>{error&&<p className="error-box span-2">{error}</p>}<button className="button button--gold span-2" disabled={busy}>{busy?"Submitting…":"Accept proposal"}</button></form>}</section></article><footer className="proposal-footer"><strong>{business.business_name||"Ironwood Remodeling"}</strong><span>{business.phone||"479.496.7819"} · {business.website||"www.ironwood-remodeling.com"}</span></footer></main>;
}
